[package]
name = "mailrs-store"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
mailrs-domain.workspace = true
rusqlite = { workspace = true, features = ["functions"] }
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
mailrs-gmail.workspace = true
tempfile.workspace = true
