[package]
name = "mailrs-cli"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "penguin-mail-cli"
path = "src/main.rs"

[dependencies]
mailrs-domain.workspace = true
mailrs-gmail.workspace = true
mailrs-store.workspace = true
mailrs-sync.workspace = true
anyhow.workspace = true
async-channel.workspace = true
chrono.workspace = true
clap.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
